### ISSUE TITLE
Some ligatures render in VSCode as a single letter stop

### ISSUE THREAD

**Issue by iansan5653** [githubnext/monaspace#115]
Please forgive my ignorance in describing this issue. I am not very familiar with font tech and I'm not even 100% sure this is a Monaspace bug and not a VSCode bug. But I think it's Monaspace because it doesn't happen with other fonts.

The problem is that some ligatures (I've noticed `->` and `=>`) register in VSCode as a single big character. This means the cursor can't go in the middle of them, resulting in a very confusing typing experience where the active cursor jumps around:

https://github.com/githubnext/monaspace/assets/2294248/fefcb65a-e868-42cb-ba25-2a118c28800b

Strangely, this doesn't always happen, like when I'm in a comment:

https://github.com/githubnext/monaspace/assets/2294248/ab7127ac-b4f7-4767-896d-8829ab25b0eb

**Comment by iansan5653** [comment]
I noticed this also happens with `</>` which is super confusing when closing JSX, particularly since it's three characters long:



https://github.com/githubnext/monaspace/assets/2294248/139c503d-a628-4da9-a852-fa052ed2f0d8

**Comment by Finii** [comment]
This is one result to the way the ligatures are formulated, see bottom part of #132 for an explanation.

**Comment by idan** [comment]
Fixed in ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0

**Comment by atreidesend** [comment]
This seems to be working fine now for the ligatures mentioned in the comments here (e.g. `/>` and `=>`), but I'm still seeing the reported behavior for `>>`, which can make lead to the same tricky ergonomics when working with typescript

Was the fix reported in https://github.com/githubnext/monaspace/commit/ca8015b27bdc6d8e1201b1ad722f4ae3c38970d0 supposed to be an exhaustive update or targeted at just those ligatures which had been reported so far?

**Comment by maxnyby** [comment]
I'm also seeing the reported behavior for `;;`, which makes it annoying and confusing to deal with semicolon-separated table data (which is quite normal in languages that use comma as decimal separator).

**Comment by Finii** [comment]
Ha, a nice writeup from someone outside monospaced fonts and how ligs work in monospaced fonts (such that they make sense):

https://joshleeb.com/posts/monospace-ligatures.html
